[package]
name = "core"
version.workspace = true
edition.workspace = true
categories.workspace = true

[dependencies]
serde = { workspace = true }
candid = { workspace = true }
validator = {workspace = true}

